#!/usr/bin/env node

var daemon = require("daemonize2").setup({
    main: "deploy.js",
    name: "deploy",
    pidfile: "deploy.pid"
});

switch (process.argv[2]) {

    case "start":
        daemon.start();
        break;

    case "stop":
        daemon.stop();
        break;

    default:
        console.log("Usage: [start|stop]");
}
